Repository adaptive-intelligent-robotics/QDax, pull requests merged in 2024-09, with the labels that each got.

#186 feat: add reevaluation function to compute corrected archives in uncertain domains
  qdax/utils/uncertainty_metrics.py
  tests/utils_test/uncertainty_metrics_test.py
Labels: enhancement, metrics

#185 Change indexing in UnstructuredRepertoire intra batch comp
  qdax/core/containers/unstructured_repertoire.py
Labels: bug

#194 style: Fix typos and add codespell pre-commit hook
  .pre-commit-config.yaml
  docs/api_documentation/core/pbt.md
  docs/overview.md
  examples/aurora.ipynb
  examples/cmaes.ipynb
  examples/cmame.ipynb
  examples/cmamega.ipynb
  examples/dads.ipynb
  examples/dcrlme.ipynb
  examples/diayn.ipynb
  examples/distributed_mapelites.ipynb
  examples/mapelites.ipynb
  examples/mees.ipynb
  examples/mome.ipynb
  examples/nsga2_spea2.ipynb
  examples/omgmega.ipynb
  examples/pga_aurora.ipynb
  examples/pgame.ipynb
  examples/qdpg.ipynb
  examples/sac_pbt.ipynb
  examples/smerl.ipynb
  examples/td3_pbt.ipynb
  qdax/baselines/cmaes.py
  qdax/baselines/dads.py
  qdax/baselines/diayn.py
  qdax/baselines/sac.py
  qdax/core/containers/archive.py
  qdax/core/containers/mapelites_repertoire.py
  qdax/core/containers/repertoire.py
  qdax/core/containers/spea2_repertoire.py
  qdax/core/containers/unstructured_repertoire.py
  qdax/core/distributed_map_elites.py
  qdax/core/emitters/cma_emitter.py
  qdax/core/emitters/cma_improvement_emitter.py
  qdax/core/emitters/cma_mega_emitter.py
  qdax/core/emitters/cma_opt_emitter.py
  qdax/core/emitters/cma_rnd_emitter.py
  qdax/core/emitters/dpg_emitter.py
  qdax/core/emitters/emitter.py
  qdax/core/emitters/mees_emitter.py
  qdax/core/emitters/omg_mega_emitter.py
  qdax/core/emitters/qdpg_emitter.py
  qdax/core/map_elites.py
  qdax/environments/__init__.py
  qdax/environments/bd_extractors.py
  qdax/environments/pointmaze.py
  qdax/tasks/README.md
  qdax/tasks/brax_envs.py
  qdax/tasks/hypervolume_functions.py
  qdax/tasks/jumanji_envs.py
  qdax/utils/plotting.py
  qdax/utils/sampling.py
  tests/baselines_test/dcrlme_test.py
  tests/baselines_test/mees_test.py
  tests/baselines_test/pgame_test.py
  tests/baselines_test/qdpg_test.py
  tests/core_test/cmaes_test.py
  tests/core_test/map_elites_test.py
  tests/core_test/neuroevolution_test/buffers_test/trajectory_buffer_test.py
  tests/utils_test/sampling_test.py
Labels: enhancement, CI
